---
apiVersion: v1
kind: Secret
metadata:
  name: object-storage-user-0
immutable: true
type: Opaque
# FIXME: change your own secret!
data:
  CONSOLE_ACCESS_KEY: T0JKSXJaUzNPRnpmSEpWZQ==
  CONSOLE_SECRET_KEY: b3hOVkpibWd4WFpjSGt5NlNrNlF6aTZzUVRxVmRYeEc=
---
apiVersion: dash.ulagbulag.io/v1alpha1
kind: ModelStorage
metadata:
  name: zone-a
spec:
  objectStorage:
    owned:
      resources:
        requests:
          storage: 1Ti
      totalNodes: 1
      totalVolumesPerNode: 1
