[package]
name = "cassette"

authors = { workspace = true }
description = { workspace = true }
documentation = { workspace = true }
edition = { workspace = true }
include = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["full"]
full = ["kubernetes"]
experimental = []

# plugins
kubernetes = ["dep:cassette-plugin-kubernetes"]

[build-dependencies]
built = { workspace = true }

[dependencies]
cassette-core = { path = "../cassette-core", features = ["ui"] }
cassette-plugin-kubernetes = { path = "../cassette-plugin-kubernetes", optional = true, features = [
    "ui",
] }

browser-panic-hook = { workspace = true }
gloo-utils = { workspace = true }
inflector = { workspace = true }
patternfly-yew = { workspace = true }
regex = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-subscriber-wasm = { workspace = true }
uuid = { workspace = true }
yew = { workspace = true }
yew-nested-router = { workspace = true }
