---
apiVersion: cassette.ulagbulag.io/v1alpha1
kind: Cassette
metadata:
  name: cdl-pond-create-shared
spec:
  component: cdl-pond-create-shared
  group: Connected Data Lake
  title: Data Pond | Create Shared
---
apiVersion: cassette.ulagbulag.io/v1alpha1
kind: CassetteComponent
metadata:
  name: cdl-pond-create-shared
spec:
  tasks:
    - name: act
      kind: Actor
      spec:
        create: true
        uri: /helm
        schema:
          create:
            - name: Namespace
              path: /namespace
              string: {}
            - name: Endpoint URL
              path: /values/remote/endpoint
              string: {}
            - name: Access Key
              path: /values/secret/value/accessKey
              string: {}
            - name: Secret Key
              path: /values/secret/value/secretKey
              string: {}
            - name: Total Quota
              path: /values/resources/requests/storage
              string: {}
            - name: Total Nodes
              path: /values/totalNodes
              number: {}
            - name: Total Volumes per Node
              path: /values/totalVolumesPerNode
              number: {}
        default:
          chartName: data-pond
          repo: https://smartx-team.github.io/connected-data-lake
          name: object-storage-pool
          namespace: name-twin
          values:
            remote:
              endpoint: https://s3.amazonaws.com
            resources:
              requests:
                storage: 10Ti
            secret:
              value:
                enabled: true
                accessKey: ""
                secretKey: ""
            storageType: Shared
            totalNodes: 1
            totalVolumesPerNode: 4
