---
apiVersion: cassette.ulagbulag.io/v1alpha1
kind: Cassette
metadata:
  name: cdl-pond-list
spec:
  component: cdl-pond-list
  group: Connected Data Lake
  title: Data Pond | List
---
apiVersion: cassette.ulagbulag.io/v1alpha1
kind: CassetteComponent
metadata:
  name: cdl-pond-list
spec:
  tasks:
    - name: list
      kind: Load
      spec:
        uri: /helm
        query:
          chartName: data-pond

    - name: filtered
      kind: Table
      spec:
        table: :/list

    - name: act
      kind: Actor
      spec:
        create: false
        delete: true
        update: false
        uri: /helm
        table: :/filtered
