---
apiVersion: cassette.ulagbulag.io/v1alpha1
kind: Cassette
metadata:
  name: cdl-endpoint-list
spec:
  component: cdl-endpoint-list
  group: Connected Data Lake
  title: Endpoint | List
---
apiVersion: cassette.ulagbulag.io/v1alpha1
kind: CassetteComponent
metadata:
  name: cdl-endpoint-list
spec:
  tasks:
    - name: list
      kind: Load
      spec:
        uri: /helm
        query:
          chartName: cdl-endpoint

    - name: filtered
      kind: Table
      spec:
        table: :/list

    - name: act
      kind: Actor
      spec:
        create: false
        delete: true
        update: false
        uri: /helm
        table: :/filtered
