---
apiVersion: cassette.ulagbulag.io/v1alpha1
kind: Cassette
metadata:
  name: cdl-zone
spec:
  component: cdl-zone
  group: Connected Data Lake
---
apiVersion: cassette.ulagbulag.io/v1alpha1
kind: CassetteComponent
metadata:
  name: cdl-zone
spec:
  tasks:
    - name: list
      kind: Load
      spec:
        url: /cdl/zone

    - name: filtered
      kind: Table
      spec:
        table: :/list

    - name: act
      kind: Actor
      spec:
        delete: true
        update: false
        uri: /cdl/zone
        values: :/filtered/table
