---
apiVersion: cassette.ulagbulag.io/v1alpha1
kind: Cassette
metadata:
  name: cdl-catalog
spec:
  component: cdl-catalog
  group: Connected Data lake
---
apiVersion: cassette.ulagbulag.io/v1alpha1
kind: CassetteComponent
metadata:
  name: cdl-catalog
spec:
  tasks:
    - name: manage
      kind: CdlCatalog
