---
apiVersion: cassette.ulagbulag.io/v1alpha1
kind: Cassette
metadata:
  name: hello-world
spec:
  component: hello-world
---
apiVersion: cassette.ulagbulag.io/v1alpha1
kind: CassetteComponent
metadata:
  name: hello-world
spec:
  tasks:
    - name: init
      kind: Variable
      spec:
        msg: |
          # Hello World
          Welcome to Cassette Player!

    - name: show-hello-message
      kind: Text
      spec:
        msg: :/init/msg
