---
apiVersion: cassette.ulagbulag.io/v1alpha1
kind: Cassette
metadata:
  name: helm-list
spec:
  component: helm-list
  group: Kubernetes Helm
---
apiVersion: cassette.ulagbulag.io/v1alpha1
kind: CassetteComponent
metadata:
  name: helm-list
spec:
  tasks:
    - name: list
      kind: Load
      spec:
        url: /helm

    - name: filtered
      kind: Table
      spec:
        table: :/list

    - name: act
      kind: Actor
      spec:
        delete: true
        update: true
        uri: /helm
        values: :/filtered/table
