---
apiVersion: cassette.ulagbulag.io/v1alpha1
kind: Cassette
metadata:
  name: helm-list
spec:
  component: helm-list
  group: MobileX
  title: List All
---
apiVersion: cassette.ulagbulag.io/v1alpha1
kind: CassetteComponent
metadata:
  name: helm-list
spec:
  tasks:
    - name: list
      kind: Load
      spec:
        uri: /helm
        query:
          namespace: name-twin

    - name: filtered
      kind: Table
      spec:
        table: :/list

    - name: act
      kind: Actor
      spec:
        create: true
        delete: true
        update: true
        uri: /helm
        table: :/filtered
