---
apiVersion: cassette.ulagbulag.io/v1alpha1
kind: Cassette
metadata:
  name: helm-actor-nvidia-isaac-sim
spec:
  component: helm-actor-nvidia-isaac-sim
  group: Kubernetes Helm
  title: "Helm Chart : NVIDIA Isaac Sim"
---
apiVersion: cassette.ulagbulag.io/v1alpha1
kind: CassetteComponent
metadata:
  name: helm-actor-nvidia-isaac-sim
spec:
  tasks:
    - name: act
      kind: Actor
      spec:
        create: true
        uri: /helm
        schema:
          create:
            - name: Chart Name
              path: /chartName
              string: {}
            - name: Chart Repository
              path: /repo
              string: {}
            - name: Name
              path: /name
              string: {}
            - name: Namespace
              path: /namespace
              string: {}
            - name: Amount of CPUs
              path: /values/resources/limits/cpu
              string:
                default: "4"
            - name: Amount of Memory
              path: /values/resources/limits/memory
              string:
                default: 16Gi
            - name: Number of GPUs
              path: /values/resources/limits/nvidia.com~1gpu
              number:
                default: 1
        default:
          chartName: nvidia-isaac-sim
          repo: https://smartx-team.github.io/mobilex-api
          name: omni01
          namespace: name-twin
