---
apiVersion: cassette.ulagbulag.io/v1alpha1
kind: Cassette
metadata:
  name: helm-actor-nvidia-isaac-sim
spec:
  component: helm-actor-nvidia-isaac-sim
  group: MobileX
  title: NVIDIA Isaac Sim
---
apiVersion: cassette.ulagbulag.io/v1alpha1
kind: CassetteComponent
metadata:
  name: helm-actor-nvidia-isaac-sim
spec:
  tasks:
    - name: act
      kind: Actor
      spec:
        create: true
        uri: /helm
        schema:
          create:
            - name: Name
              path: /name
              string: {}
            - name: Namespace
              path: /namespace
              string: {}
            - name: Amount of CPUs
              path: /values/resources/limits/cpu
              string: {}
            - name: Amount of Memory
              path: /values/resources/limits/memory
              string: {}
            - name: Number of GPUs
              path: /values/resources/limits/nvidia.com~1gpu
              number:
                default: 1
        default:
          chartName: nvidia-isaac-sim
          repo: https://smartx-team.github.io/mobilex-api
          name: omni01
          namespace: name-twin
          values:
            resources:
              limits:
                cpu: "11"
                memory: 31Gi
