---
apiVersion: cassette.ulagbulag.io/v1alpha1
kind: Cassette
metadata:
  name: helm-actor-mobilex-vstation
spec:
  component: helm-actor-mobilex-vstation
  group: Kubernetes Helm
  title: "Helm Chart : MobileX vStation"
---
apiVersion: cassette.ulagbulag.io/v1alpha1
kind: CassetteComponent
metadata:
  name: helm-actor-mobilex-vstation
spec:
  tasks:
    - name: act
      kind: Actor
      spec:
        create: true
        uri: /helm
        schema:
          create:
            - name: Name
              path: /name
              string: {}
            - name: Namespace
              path: /namespace
              string: {}
            - name: IP Address
              path: /values/service/loadBalancerIP
              string:
                default: "0.0.0.0"
            - name: Password
              path: /values/serviceAccount/password
              string: {}
            - name: Amount of CPUs
              path: /values/resources/limits/cpu
              string: {}
            - name: Amount of Memory
              path: /values/resources/limits/memory
              string: {}
            - name: Number of GPUs
              path: /values/resources/limits/nvidia.com~1gpu
              number: {}
        default:
          chartName: mobilex-vstation
          repo: https://smartx-team.github.io/mobilex-api
          name: vstation01
          namespace: name-twin
          values:
            resources:
              limits:
                cpu: "11"
                memory: 31Gi
                nvidia.com/gpu: 1
            service:
              type: LoadBalancer
            serviceAccount:
              password: "myPassword!"
