---
apiVersion: cassette.ulagbulag.io/v1alpha1
kind: Cassette
metadata:
  name: kubernetes-list
spec:
  component: kubernetes-list
  group: Kubernetes
---
apiVersion: cassette.ulagbulag.io/v1alpha1
kind: CassetteComponent
metadata:
  name: kubernetes-list
spec:
  tasks:
    - name: apiVersion
      kind: TextInput
      spec:
        default: apps/v1
        label: API Version

    - name: kind
      kind: TextInput
      spec:
        default: Deployments
        label: Resource Kind

    - name: list
      kind: KubernetesList
      spec:
        apiVersion: :/apiVersion/text
        kind: :/kind/text
        namespaced: true

    - name: show-head
      kind: Text
      spec:
        msg: "# Output"

    - name: show
      kind: Text
      spec:
        msg: :/list/content
