---
apiVersion: cassette.ulagbulag.io/v1alpha1
kind: Cassette
metadata:
  name: mobilex-vstation-create
spec:
  component: mobilex-vstation-create
  group: MobileX
  title: MobileX vStation
---
apiVersion: cassette.ulagbulag.io/v1alpha1
kind: CassetteComponent
metadata:
  name: mobilex-vstation-create
spec:
  tasks:
    - name: act
      kind: Actor
      spec:
        create: true
        uri: /helm
        schema:
          create:
            - name: Name
              path: /name
              string: {}
            - name: Namespace
              path: /namespace
              string: {}
            - name: IP Address
              path: /values/service/loadBalancerIP
              string:
                default: "0.0.0.0"
            - name: Password
              path: /values/serviceAccount/password
              string: {}
            - name: Amount of CPUs
              path: /values/resources/limits/cpu
              string: {}
            - name: Amount of Memory
              path: /values/resources/limits/memory
              string: {}
            - name: Amount of Storage
              path: /values/storage/resources/requests/storage
              string: {}
            - name: Number of GPUs
              path: /values/resources/limits/nvidia.com~1gpu
              number: {}
        default:
          chartName: mobilex-vstation
          repo: https://smartx-team.github.io/connected-data-lake
          name: vstation01
          namespace: name-twin
          values:
            resources:
              limits:
                cpu: "11"
                memory: 31Gi
                nvidia.com/gpu: 1
            service:
              type: LoadBalancer
            serviceAccount:
              password: "myPassword!"
            storage:
              resources:
                requests:
                  storage: 10Ti
