---
apiVersion: cassette.ulagbulag.io/v1alpha1
kind: Cassette
metadata:
  name: openai-chat
spec:
  component: openai-chat
  group: OpenAI
---
apiVersion: cassette.ulagbulag.io/v1alpha1
kind: CassetteComponent
metadata:
  name: openai-chat
spec:
  tasks:
    - name: init
      kind: TextInput
      spec:
        label: What are you curious about?
        placeholder: "Which is better: Diet Coke vs Normal Coke"

    - name: chat
      kind: OpenAIChat
      spec:
        baseUrl: /v1
        message: :/init/text
        stream: true
        # messages:
        #   - role: user
        #     content: "Which is better: Diet Coke vs Normal Coke"

    - name: show
      kind: Text
      spec:
        msg: :/chat/content
        progress: :/chat/progress
