name: ci

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Install trunk
        uses: jetli/trunk-action@v0
        with:
          version: "latest"

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install node dependencies
        run: npm clean-install

      - name: Disable terminal hooks
        run: sed -i '/\[\[hooks\]\]/,$d' 'Trunk.toml'

      - name: Build
        run: trunk build

  build-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            cmake \
            libhwloc-dev \
          && sudo apt-get clean all \
          && sudo rm -rf /var/lib/apt/lists/*

      - name: Build
        run: cargo build --package cassette-gateway --package cassette-operator --features 'full,experimental' --verbose

      - name: Run tests
        run: cargo test --package cassette-gateway --package cassette-operator --features 'full,experimental' --verbose
