name: lint

on:
  push:
    paths:
      - "**.rs"
      - "**.toml"
      - "**.yaml"
      - "**.yml"
  pull_request:
    paths:
      - "**.rs"
      - "**.toml"
      - "**.yaml"
      - "**.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-deny:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Install cargo-deny
        run: cargo install cargo-deny

      - name: Check cargo-deny
        run: cargo deny check --show-stats

  rustfmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          components: rustfmt

      - name: Run rustfmt
        uses: actions-rust-lang/rustfmt@v1
