name: pr_check

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          profile: minimal

      - name: Install trunk
        uses: jetli/trunk-action@v0.1.0
        with:
          version: "latest"

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install node dependencies
        run: npm clean-install

      - name: Disable terminal hooks
        run: sed -i '/\[\[hooks\]\]/,$d' 'Trunk.toml'

      - name: Build
        run: trunk build

  build-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Check clippy
        run: cargo clippy --all --verbose

      - name: Build
        run: cargo build --all --verbose

      - name: Run tests
        run: cargo test --all --verbose
